### ISSUE TITLE
Extract d3sequence into its own repo

### ISSUE THREAD

**Issue by udp** [graik/rotmic#26]
Would be nice to extract d3sequence and maintain it as an individual project (maybe with a more standard JS license like MIT rather than AGPL?)

We could then submit it to npm and BioJS.

**Comment by graik** [comment]
Thanks for the reminder. Let's go for MIT license then. I've got some time now.

**Comment by graik** [comment]
Done. I have made you collaborator on: https://github.com/graik/d3seq
Feel free to work on it there or fork it elsewhere :)

What is still missing is a full example file.
