### ISSUE TITLE
sequence view blocked by https redirect (heroku branch)

### ISSUE THREAD

**Issue by graik** [graik/rotmic#30]
The javascript sequence view (template: dnacomponent/readonly.html) is blocked by the HTTPS redirect. The problem seems to be the dependency on the external D3 javascript library.

In the template file (dnacomponent/readonly.html):
```django
{% block extrahead %}{{ block.super }}
<!--{% benchling_libs %} -->
    {% seqdisplay_libs %}
{% endblock %}
```
translates into this page source:
```html
    <script src='http://d3js.org/d3.v3.min.js' charset='utf-8'></script>
```
The HTTP address of d3js seems to be disrupted as *all* requests are translated to https.

probable solution:
------------------------
* copy d3.js into rotmic static folder and load it from there.

**Comment by dunatotatos** [comment]
Tested, merged, and deployed.
Thank you :)
